name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '${{ github.repository }}'
    runs-on: windows-2022
    strategy:
      matrix:
        os: [windows-2022]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Cache Qt Install
      id: cache-qt6
      uses: actions/cache@v4
      with:
        path: qt6_673_static_64
        key: ${{ runner.os }}-qt6_673_static_64

    - name: Install Static Qt
      if: steps.cache-qt6.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest https://github.com/microcai/static-build-qt6/releases/download/qt6_673_static_64/qt6_673_static_64.zip -OutFile .\qt6_673_static_64.zip
        expand-archive -path "qt6_673_static_64.zip"

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install" -DCMAKE_PREFIX_PATH=qt6_673_static_64/Qt6_binaries -B build
        cmake --build build
        cmake --install build

    - name: zip the result
      run: |
        cd install/bin
        7z a eda-tool-win64.zip edatool.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          auto release by tag push
        draft: false
        prerelease: false
    - name: upload Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: install/bin/eda-tool-win64.zip
    - name: Upload generic artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: eda-tool-win64
        path: install/bin
